config/routes.rb
Rails.application.routes.draw do
  
  get 'orders/index'
  root 'products#index'
  
  devise_for :users
	resources :contact, only: [:index]
  resources :products

  resources :users, only: [:show] do
    resources :carts, only: [:show] do
      resources :charges, only: [:new, :create]
    end
  end

 
  

  resources :product_carts, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_one :user
    has_many :product_carts
    has_many :products, through: :product_carts
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products

    validates :name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user

    has_many :product_orders
    has_many :products, through: :product_orders
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    has_many :product_carts
    has_many :carts, through: :product_carts
  
    has_many :product_orders
    has_many :orders, through: :product_orders
  
    validates :name, presence: true
    validates :url, presence: true
    validates :description, presence: true
    validates :price, presence: true, numericality: { greater_than: 0, less_than: 100 }

end

app/models/product_cart.rb
class ProductCart < ApplicationRecord
    belongs_to :cart
    belongs_to :product
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
    belongs_to :order
    belongs_to :product
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   
  has_one :cart
  has_many :orders

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource_or_scope)
        session[:user_id] = current_user.id
        @cart = Cart.new(user_id: current_user.id)
        if @cart.save
          root_path
        end
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:show]


  def show
    @cart = Cart.find(params[:id])

    @productcart = ProductCart.where(cart_id: params[:id])
    @total_price = 0
    @productcart.each do |productcart|
      @total_price = productcart.product.price  + @total_price
    end
    
    only_see_own_page
  end

  private

  def only_see_own_page
    @cart = Cart.find(params[:id])
  
    if @cart.user_id != current_user.id
      redirect_to root_path, notice: "Vous n'avez pas accès a cette page."
    end
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @cart = Cart.find_by!(id: session[:cart_id], user: session[:user_id])
    @productcart = ProductCart.where(cart_id: params[:cart_id])
    @total_price = 0
    @productcart.each do |productcart|
      @total_price = productcart.product.price  + @total_price
    end
    
  end
  
  def create
    # Amount in cents
    @cart = Cart.find(params[:cart_id])
    @productcart = ProductCart.where(cart_id: params[:cart_id])
    @total_price = 0
    @productcart.each do |productcart|
      @total_price = productcart.product.price  + @total_price
    end
    @amount = @total_price * 100
    
    @current_user = User.find(params[:user_id])
    order = Order.create(user_id: current_user.id)
    @productcart = ProductCart.where(cart_id: params[:cart_id])
    @productcart.each do |productcart|
      ProductOrder.create(order_id: order.id, product_id: productcart.product.id, quantity: 1, total_price: productcart.product.price)
    end
    
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })
    
    Order.find(order.id).update(stripe_customer_id: customer.id)
    @cart = Cart.where(user_id: current_user.id)
    @user_cart = ProductCart.where(cart: @cart)
    @user_cart.each do |product| ProductCart.find(product.id).destroy end
    redirect_to user_path(@current_user)
    
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
  
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all
    

    @productcart = ProductCart.where(cart_id: params[:id])
    @total_price = 0
    @productcart.each do |productcart|
    @total_price = productcart.product.price  + @total_price
    
    end
  end

  def new
    @order = Order.new

    @cart = Cart.find(params[:id])

    @productcart = ProductCart.where(cart_id: params[:id])
    @total_price = 0
    @productcart.each do |productcart|
    @total_price = productcart.product.price  + @total_price
    end
  end

  

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
      @product = Product.all
      @category = Category.all

    end

    def show
      @product = Product.find_by_id(params[:id])


    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :is_owner?, only: [:show]

  def show
    @user = current_user
    
  end

  private 

  def is_owner?
    if current_user.id.to_i != params[:id].to_i
      flash[:danger] = "Vous ne pouvez pas acceder à cette page"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
 
end

app/helpers/carts_helper.rb
module CartsHelper
 
end

app/helpers/charge_helper.rb
module ChargeHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_cart_helper.rb
module ProductCartHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/carts/show.html.erb
<div class="container mt-5 mb-5">
    <div class="d-flex justify-content-center row">
        <div class="col-md-8">
            <div class="p-2">
                <h4>Votre panier</h4>
            </div>

            <%@productcart.each do |e|%>
                <div class="d-flex flex-row justify-content-between align-items-center p-2 bg-white mt-4 px-3 rounded">
                    <div class="mr-1"><img class="rounded" src= "<%=e.product.url%>" width="70"></div>
                    <div class="d-flex flex-column align-items-center product-details"><span class="font-weight-bold"><%=e.product.name%></span>
                        <div class="d-flex flex-row product-desc">
                            <div class="color"><span class="text-grey"><%e.product.category%></span></div>
                        </div>
                    </div>
                
                    <div>
                        <h5 class="text-grey"><%=e.product.price%> € </h5>
                    </div>
                    <%= link_to product_cart_path(cart_id: e.id), title: "Supprimer",data: { confirm: "Êtes-vous sûr ?" }, method: :delete do %>
                        <i class="fa fa-trash mb-1 text-danger"></i>                    
                    <% end %>
                    <%= link_to "voir plus", product_path(e.product.id), class: 'btn btn-outline-warning btn-sm ml-2 mr-0 text-warning'%>
                </div>
            <%end%>
           <% if @total_price > 0 %>
                <%= form_tag user_cart_charges_path(cart_id: params[:id]) do %>
                    <article>
                        <% if flash[:error].present? %>
                        <div id="error_explanation">
                            <p><%= flash[:error] %></p>
                        </div>
                        <% end %>
                        <label class="amount">
                        <span>Montant: <%= @total_price %> €</span>
                        </label>
                    </article>

                    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                            data-description="A month's subscription"
                            data-amount=<%= @total_price * 100%>
                            data-locale="auto"></script>
                <% end %>
            <% end %>






        </div>
    </div>
</div>

app/views/products/index.html.erb
<section class="p-0 height-700 parallax-bg" style="background-image: url(https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1027&q=80)">
        <div class="container h-100">
            <div class="row justify-content-between align-items-center h-100">
                <div class="col-md-8 mb-7">
                    <h4 class="text-white">Trouvez les plus belles images du web !</h4>
                    <h1 class="display-4 font-weight-bold text-white">Bienvenue au royaume des chats</h1>
                </div>
            </div>
        </div>
    </section>

<section class="portfolio portfolio-style-2 pb-0">
			<div class="container">
				<div class="row">
					<div class="col-md-12 p-0">
						<div class="nav justify-content-center">
							<ul class="nav-tabs nav-tabs-style-3 text-center px-2 p-md-0 m-0 mb-4">
								<li class="nav-filter active" data-filter="*">Toutes les images</li>
								<% (@category.count).times do |count| %>
									<li class="nav-filter" data-filter=".<%= count +1 %>"><%=@category.find(count +1).name %>   </li>
								<% end %>
							</ul>
						</div>
					</div>
				</div>
			</div>
</section>
	<section class="portfolio pb-0">
		<div class="container">
			<div class="row">
				<div class="col-md-12 p-0">
					<div class="portfolio-wrap grid items-4 items-padding">
						<!-- portfolio-card -->
						<% for product in @product %>
							<div class="portfolio-card isotope-item <%= product.category_id %> ">
								<div class="portfolio-card-body">
									
									<div class="portfolio-card-footer">


										<img class="card-img" src="<%=product.url %>" alt="Card image cap">
										<h6 class="info-title"><a href="<%=product_path(product.id)%>" title=""><%=product.name %></a></h6>
										<h6>Prix <%=product.price %>€ </h6>
										<% if user_signed_in? %>
											<%= link_to "Ajouter au panier !", product_carts_path(product_id: product.id), method: :post, class: 'btn btn-primary mr-0 text-light' %> 										
										<% else %>
                							<%= link_to "Au panier !", new_user_session_path, class: 'btn btn-primary  mr-0 text-light'%>
										<%end%>
									</div>
								</div>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</section>

	


	

app/views/products/show.html.erb
<div class="card mx-auto my-4 shadow" style="width: 30rem;">
<img class="card-img" src= "<%= @product.url%>" alt="Card image cap">
<div class="card-body">
    <h5 class="card-title"> <%= @product.name%> </h5>
    <p class="card-text"><%= @product.description%></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Prix : <%= @product.price%>€</li>
    
    <li class="list-group-item">Categorie : <%= @product.category.name%></li>
  </ul>
  
    <div class="card-body">
      
      <%= link_to "Retourner au catalogue", products_path,  :class => "btn btn-primary" %>
      <% if user_signed_in? %>
				<%= link_to "Ajouter au panier !", product_carts_path(product_id: @product.id), method: :post, class: 'btn btn-primary ml-2 mr-0 text-light' %> 										
			<% else %>
        <%= link_to "Au panier !", new_user_session_path, class: 'btn btn-primary  ml-2 mr-0 text-light'%>
			<%end%>
    </div>
  
</div>