config/routes.rb
Rails.application.routes.draw do
  
  get 'orders/index'
  root 'products#index'
  
  devise_for :users
	resources :contact, only: [:index]
  resources :products

  resources :users, only: [:show] do
    resources :carts, only: [:show] do
      resources :charges, only: [:new, :create]
    end
  end

 
  

  resources :product_carts, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_one :user
    has_many :product_carts
    has_many :products, through: :product_carts
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products

    validates :name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user

    has_many :product_orders
    has_many :products, through: :product_orders
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    has_many :product_carts
    has_many :carts, through: :product_carts
  
    has_many :product_orders
    has_many :orders, through: :product_orders
  
    validates :name, presence: true
    validates :url, presence: true
    validates :description, presence: true
    validates :price, presence: true, numericality: { greater_than: 0, less_than: 100 }

end

app/models/product_cart.rb
class ProductCart < ApplicationRecord
    belongs_to :cart
    belongs_to :product
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
    belongs_to :order
    belongs_to :product
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   
  has_one :cart
  has_many :orders

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
       
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:show]


  def show
    @cart = Cart.find(params[:id])

    @productcart = ProductCart.where(cart_id: params[:id])
    @total_price = 0
    @productcart.each do |productcart|
      @total_price = productcart.product.price  + @total_price
    end
    
    only_see_own_page
  end

  private

  def only_see_own_page
    @cart = Cart.find(params[:id])
  
    if @cart.user_id != current_user.id
      redirect_to root_path, notice: "Vous n'avez pas accès a cette page."
    end
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @cart = Cart.find_by!(id: session[:cart_id], user: session[:user_id])
    @productcart = ProductCart.where(cart_id: params[:cart_id])
    @total_price = 0
    @productcart.each do |productcart|
      @total_price = productcart.product.price  + @total_price
    end
    
  end
  
  def create
    # Amount in cents
    @cart = Cart.find(params[:cart_id])
    @productcart = ProductCart.where(cart_id: params[:cart_id])
    @total_price = 0
    @productcart.each do |productcart|
      @total_price = productcart.product.price  + @total_price
    end
    @amount = @total_price * 100
    
    @current_user = User.find(params[:user_id])
    order = Order.create(user_id: current_user.id)
    @productcart = ProductCart.where(cart_id: params[:cart_id])
    @productcart.each do |productcart|
      ProductOrder.create(order_id: order.id, product_id: productcart.product.id, quantity: 1, total_price: productcart.product.price)
    end
    
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })
    
    Order.find(order.id).update(stripe_customer_id: customer.id)
    @cart = Cart.where(user_id: current_user.id)
    @user_cart = ProductCart.where(cart: @cart)
    @user_cart.each do |product| ProductCart.find(product.id).destroy end
    redirect_to user_path(@current_user)
    
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
  
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all
    

    @productcart = ProductCart.where(cart_id: params[:id])
    @total_price = 0
    @productcart.each do |productcart|
    @total_price = productcart.product.price  + @total_price
    
    end
  end

  def new
    @order = Order.new

    @cart = Cart.find(params[:id])

    @productcart = ProductCart.where(cart_id: params[:id])
    @total_price = 0
    @productcart.each do |productcart|
    @total_price = productcart.product.price  + @total_price
    end
  end

  

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
      @product = Product.all
      @category = Category.all

    end

    def show
      @product = Product.find_by_id(params[:id])


    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :is_owner?, only: [:show]

  def show
    @user = current_user
    
  end

  private 

  def is_owner?
    if current_user.id.to_i != params[:id].to_i
      flash[:danger] = "Vous ne pouvez pas acceder à cette page"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
 
end

app/helpers/carts_helper.rb
module CartsHelper
 
end

app/helpers/charge_helper.rb
module ChargeHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_cart_helper.rb
module ProductCartHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/charges/create.html.erb
<h2>Merci, votre paiement d'un montant de <strong><%= @amount / 100 %></strong>est validé!</h2>

app/views/charges/new.html.erb
<%= form_tag user_cart_charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Montant: <%= @total_price %> €</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount=<%= @total_price * 100%>
          data-locale="auto"></script>
<% end %>

app/views/contact/index.html.erb
<body>

	<!-- =======================
	Banner innerpage -->
	<div class="text-center bg-overlay-dark-4" style="background:url(https://images.pexels.com/photos/3163612/pexels-photo-3163612.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940) no-repeat; background-size: cover; background-position: center center;">
		<div class="container">
			<div class="row all-text-white">
				<div class="col-md-12 align-self-center">
					<h6 class="display-4 mt-9 mb-0" style="font-size: 7em">A propos</h6>
				</div>
			</div>
		</div>
	</div>
	<!-- =======================
	Banner innerpage -->

	<!-- =======================
	contact -->
	<section class="contact-page">
		<div class="container">
			<div class="row">
				<div class="col-12 col-lg-8 mx-auto">
					<div class="title text-center">
						<h2>Chat alors, on aurait pas oublié de se présenter ?</h2>
					</div>
				</div>
			</div>
			<br>
			<div class="row" style="justify-content: space-evenly;">
				<div class="col-md-6">
					<div class="contact-box h-150 bg-overlay-dark-7 px-3 py-4" style="background:url(https://images.pexels.com/photos/3069334/pexels-photo-3069334.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940) no-repeat; background-size: cover; background-position: center center; border-radius: 30px;overflow:hidden;">
						<!-- Phone -->
						<div class="contact-info all-text-white">
							<h2 class="mb-2">L'équipe, c'est :</h2>
							<br>
							<br>
							<br>
							<ul style="list-style-type:circle;">
								<li style="font-size: 1.6em; padding-left: 10px; ">Samira Adidaoui<small>, éleveuse de chats de tout poil</small></li>
								<br>
								<br>
								<li style="font-size: 1.6em; padding-left: 10px;">Marine Kouadio<small>, experte en félinologie</small></li>
																<br>
																<br>
								<li style="font-size: 1.6em; padding-left: 10px;">Guillaume Redon<small>, négociant de gros matous</small></li>
																<br>
																<br>

								<li style="font-size: 1.6em; padding-left: 10px;">Alex Balomog<small>, chasseur de chats de gouttière</small></li>
								<br>
								<br>

								<li style="font-size: 1.6em; padding-left: 10px;">Brice Arby<small>, adepte de minet-ralogie</small></li>
							</ul>
						</div>
					</div>
				</div>
				<!-- google map -->
			
				<!-- contact form -->

			</div>
		</div>				
		<br>
		<br>
		<br>
		<br>
		<div class="row">
				<div class="col-12 col-lg-8 mx-auto">
					<div class="title text-center">
						<h4>Une suggestion ? Une remarque ? Une question ?</h4>
						<h4>Vous pouvez nous écrire à l'adresse suivante : <a href="#">contact@kittenofTHP.com</a></h4>
					</div>
				</div>
			</div>
	</section>
	
	



</body>
</html>

app/views/users/show.html.erb
<div class="row">
  	<div class="col-md-3" style="background-image: url(https://images.unsplash.com/photo-1566458226966-5d1efe19e4b7?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8OHx8a2l0dGVufGVufDB8fDB8&auto=format&fit=crop&w=500&q=60"></div>
  	<div class="col-md-1"></div>
  	<div class="col-md-5">
  		<br>
  		<br>
  		<br>
    	<div class="card">
  			<div class="card-body">
     			<h1 class="font-weight-bold">Récapitulatif de mes infos personnels :</h1>
     			
				<ul class="list-group">
  					<li class="list-group-item"><p>Prénom</b> : <%= @user.first_name %></p></li>
  					<br>
    				<li class="list-group-item"><p>Nom</b> : <%= @user.last_name %></p></li>
    				<br>
					<li class="list-group-item"><p>E-mail</b> : <%= @user.email %></p></li>
				</ul>
				<hr>
	    		<p>Pour l'instant, j'ai passé <%= @user.orders.all.count %> commande(s) sur le site.</p>
	    		<hr>
					<div>
					<p>Je souhaite modifier mon adresse e-mail ou mon mot de passe ?</p>
	   			<a href="/users/edit" class="btn btn-primary" >C'est par ici !</a>
					</div>
						<div>
					<p>Voir mes commandes ?</p>
					<%= link_to "Voir mes commandes", orders_index_path, class: "btn btn-primary"%>
	   			
					</div>
  			</div>
		</div>

		<br>
		<br>
		<br>
	</div>
</div>