config/routes.rb
Rails.application.routes.draw do
  
  get 'orders/index'
  root 'products#index'
  
  devise_for :users
	resources :contact, only: [:index]
  resources :products

  resources :users, only: [:show] do
    resources :carts, only: [:show] do
      resources :charges, only: [:new, :create]
    end
  end

 
  

  resources :product_carts, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_one :user
    has_many :product_carts
    has_many :products, through: :product_carts
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products

    validates :name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user

    has_many :product_orders
    has_many :products, through: :product_orders
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    has_many :product_carts
    has_many :carts, through: :product_carts
  
    has_many :product_orders
    has_many :orders, through: :product_orders
  
    validates :name, presence: true
    validates :url, presence: true
    validates :description, presence: true
    validates :price, presence: true, numericality: { greater_than: 0, less_than: 100 }

end

app/models/product_cart.rb
class ProductCart < ApplicationRecord
    belongs_to :cart
    belongs_to :product
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
    belongs_to :order
    belongs_to :product
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   
  has_one :cart
  has_many :orders

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
       
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:show]


  def show
    @cart = Cart.find(params[:id])

    @productcart = ProductCart.where(cart_id: params[:id])
    @total_price = 0
    @productcart.each do |productcart|
      @total_price = productcart.product.price  + @total_price
    end
    
    only_see_own_page
  end

  private

  def only_see_own_page
    @cart = Cart.find(params[:id])
  
    if @cart.user_id != current_user.id
      redirect_to root_path, notice: "Vous n'avez pas accès a cette page."
    end
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @cart = Cart.find_by!(id: session[:cart_id], user: session[:user_id])
    @productcart = ProductCart.where(cart_id: params[:cart_id])
    @total_price = 0
    @productcart.each do |productcart|
      @total_price = productcart.product.price  + @total_price
    end
    
  end
  
  def create
    # Amount in cents
    @cart = Cart.find(params[:cart_id])
    @productcart = ProductCart.where(cart_id: params[:cart_id])
    @total_price = 0
    @productcart.each do |productcart|
      @total_price = productcart.product.price  + @total_price
    end
    @amount = @total_price * 100
    
    @current_user = User.find(params[:user_id])
    order = Order.create(user_id: current_user.id)
    @productcart = ProductCart.where(cart_id: params[:cart_id])
    @productcart.each do |productcart|
      ProductOrder.create(order_id: order.id, product_id: productcart.product.id, quantity: 1, total_price: productcart.product.price)
    end
    
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })
    
    Order.find(order.id).update(stripe_customer_id: customer.id)
    @cart = Cart.where(user_id: current_user.id)
    @user_cart = ProductCart.where(cart: @cart)
    @user_cart.each do |product| ProductCart.find(product.id).destroy end
    redirect_to user_path(@current_user)
    
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all
    

    @productcart = ProductCart.where(cart_id: params[:id])
    @total_price = 0
    @productcart.each do |productcart|
    @total_price = productcart.product.price  + @total_price
    
    end
  end

  def new
    @order = Order.new

    @cart = Cart.find(params[:id])

    @productcart = ProductCart.where(cart_id: params[:id])
    @total_price = 0
    @productcart.each do |productcart|
    @total_price = productcart.product.price  + @total_price
    end
  end

  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :is_owner?, only: [:show]

  def show
    @user = current_user
    
  end

  private 

  def is_owner?
    if current_user.id.to_i != params[:id].to_i
      flash[:danger] = "Vous ne pouvez pas acceder à cette page"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
 
end

app/helpers/carts_helper.rb
module CartsHelper
 
end

app/helpers/charge_helper.rb
module ChargeHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_cart_helper.rb
module ProductCartHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert-dismissible fade show alert alert-<%= key %>"><%= value %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- =======================
	footer  -->
	<footer class="footer bg-light">
		
		<div class="divider "></div>
		<!--footer copyright -->
		<div class="footer-copyright pb-3">
			<div class="container">
				<div class="d-md-flex justify-content-between align-items-center py-3 text-center text-md-left">
					<!-- copyright text -->
					<div class="copyright-text">©2020 All Rights Reserved by <a href="#!"> TeamCat.</a></div>
					<!-- copyright links-->
					<div class="copyright-links primary-hover mt-3 mt-md-0">
						<ul class="list-inline">
							
              <%=link_to "Accueil", root_path, :class => "list-inline-item pl-2"%>
              <%= link_to "Contact", contact_index_path, :class => "list-group-item-action"%>
							<li class="list-inline-item pl-2"><a class="list-group-item-action pr-0"><i class="fab fa-instagram"></i></a></li>
							<li class="list-inline-item pl-2"><a class="list-group-item-action pr-0"><i class="fab fa-facebook"></i></a></li>
							<li class="list-inline-item pl-2"><a class="list-group-item-action pr-0"><i class="fab fa-twitter"></i></a></li>
							<li class="list-inline-item pl-2"><a class="list-group-item-action" href="#">Politique de confidentialité</a></li>
							<li class="list-inline-item pl-2"><a class="list-group-item-action pr-0" href="#">CGV</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</footer>
	

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="d-flex justify-content-start">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
           <i class="fas fa-cat fa-4x"></i>          
          </li>
          <li class="nav-item active">
            <%= link_to "Accueil", root_path, :class => "nav-link" %>
          </li>
          <%if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Mon Compte
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              
              <%= link_to "Mon Profil", user_path(:id => current_user.id), :class => "dropdown-item" %>
              <%= link_to "Deconnexion", destroy_user_session_path, method: :delete, :class => "dropdown-item" %>
            </div>
          </li>
          <%else %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Mon Compte
              </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                
                <%= link_to "Se connecter", new_user_session_path, :class => "dropdown-item" %>
                <%= link_to "Nouveau client?",  new_user_registration_path, :class => "dropdown-item"%>
              </div>
            </li>
          <%end%>
        </ul>
      </div>
      <div class="d-flex justify-content-end">
        <ul class="navbar-nav mr-auto" >
          <% if user_signed_in?%>
          <li class="nav-item p-2">
            <%= link_to "Mon Panier", user_cart_path(:user_id => current_user.id, id: Cart.where(user_id: current_user.id).last), :class => "nav-link" %>
          </li>
          <% end %>
          <li class="nav-item p-2">
            <%= link_to "A Propos", contact_index_path, :class => "nav-link" %>
          </li>
        </ul>
      </div> 
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppChaton</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   <script src="https://kit.fontawesome.com/18f2e2cbfa.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= render 'layouts/flash'%>
    
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  
    <%= render 'layouts/footer'%>
  </body>
   
  
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>